import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/state/provider";

const font = Space_Mono({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  // adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} h-screen w-screen overflow-hidden`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
